import type { Car, CarFeature, CarType } from './types';

export const cars: Car[] = [
  {
    id: 'c3',
    name: 'Avanza',
    type: 'Van',
    passengers: 7,
    luggage: 3,
    pricePerDay: 600000,
    imageId: 'avanza-car',
    features: ['Automatic Transmission', 'Air Conditioning'],
  },
  {
    id: 'c1',
    name: 'All New Avanza',
    type: 'Van',
    passengers: 7,
    luggage: 4,
    pricePerDay: 700000,
    imageId: 'all-new-avanza',
    features: ['Automatic Transmission', 'Air Conditioning'],
  },
  {
    id: 'c5',
    name: 'Xpander',
    type: 'SUV',
    passengers: 7,
    luggage: 4,
    pricePerDay: 700000,
    imageId: 'xpander-car',
    features: ['Automatic Transmission', 'Air Conditioning', 'GPS'],
  },
  {
    id: 'c6',
    name: 'Innova Reborn',
    type: 'SUV',
    passengers: 7,
    luggage: 5,
    pricePerDay: 900000,
    imageId: 'innova-reborn',
    features: ['Automatic Transmission', 'Air Conditioning', 'GPS'],
  },
  {
    id: 'c9',
    name: 'Hiace Commuter',
    type: 'Van',
    passengers: 14,
    luggage: 10,
    pricePerDay: 1100000,
    imageId: 'hiace-commuter',
    features: ['Manual Transmission', 'Air Conditioning'],
  },
  {
    id: 'c10',
    name: 'Hiace Premio',
    type: 'Van',
    passengers: 12,
    luggage: 8,
    pricePerDay: 1300000,
    imageId: 'hiace-premio',
    features: ['Manual Transmission', 'Air Conditioning', 'GPS'],
  },
  {
    id: 'c7',
    name: 'Toyota Alphard',
    type: 'Luxury',
    passengers: 6,
    luggage: 4,
    pricePerDay: 1500000,
    imageId: 'toyota-alphard',
    features: ['Automatic Transmission', 'Air Conditioning', 'GPS', 'Child Seat'],
  },
  {
    id: 'c8',
    name: 'Toyota Vellfire',
    type: 'Luxury',
    passengers: 6,
    luggage: 4,
    pricePerDay: 1500000,
    imageId: 'toyota-vellfire',
    features: ['Automatic Transmission', 'Air Conditioning', 'GPS', 'Child Seat'],
  },
];

export const carTypes: CarType[] = ['Sedan', 'SUV', 'Van', 'Luxury'];
export const carFeatures: CarFeature[] = [
  'GPS',
  'Child Seat',
  'Automatic Transmission',
  'Air Conditioning',
  'Manual Transmission',
];
